name: Yaml Lint

on: [push, pull_request]

jobs:
    yamllint:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.1.0

          - name: Run yamllint
            uses: ansible-actions/yamllint-action@v0.0.1
            with:
              target: "items"